"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR aponta para a pasta 'Humap Back/HuMap/Back-end'
BASE_DIR = Path(__file__).resolve().parent.parent

# --- CARREGA O ARQUIVO .ENV ---
# Isso procura o arquivo .env na mesma pasta do manage.py (BASE_DIR)
load_dotenv(BASE_DIR / '.env')

# --- CONFIGURAÇÃO DE INTEGRAÇÃO COM FRONT-END ---
# Define onde está a pasta 'src' do Front-end em relação ao Back-end.
FRONTEND_DIR = BASE_DIR.parent / 'Front-end' / 'src'


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-chave-padrao-para-dev')

# SECURITY WARNING: don't run with debug turned on in production!
# Compara a string do .env para retornar True ou False
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# --- ALTERAÇÃO PARA DEPLOY NO RENDER ---
# Define os hosts permitidos. '*' permite todos (mais fácil para deploy inicial).
# Em produção rigorosa, você usaria ['.onrender.com', 'seu-dominio.com']
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Apps de terceiros
    'corsheaders',
    'rest_framework',
    # Seus Apps
    'users',
    'feed',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Essencial para arquivos estáticos
    'corsheaders.middleware.CorsMiddleware', # Middleware do CORS
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Aqui dizemos ao Django para buscar os HTMLs na pasta src do Front-end
        'DIRS': [FRONTEND_DIR], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# --- CONFIGURAÇÃO DE BANCO DE DADOS ---
# Tenta usar PostgreSQL se disponível (Render/Vercel/Neon), senão usa SQLite
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Configuração para o Render (PostgreSQL)
database_url = os.getenv('DATABASE_URL')
if database_url:
    DATABASES['default'] = dj_database_url.parse(database_url, conn_max_age=600)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Recife'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Configuração essencial:
# Diz ao Django para procurar arquivos estáticos (css, js, assets) na pasta src do Front-end
STATICFILES_DIRS = [
    FRONTEND_DIR,
]

# Configuração para quando rodar o collectstatic no servidor
STATIC_ROOT = BASE_DIR / 'staticfiles'

# --- CONFIGURAÇÃO DO WHITENOISE PARA RENDER ---
# Isso garante que o Django sirva os arquivos de forma otimizada
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Configurações de Mídia (Uploads de usuários)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configurações Adicionais
CORS_ALLOW_ALL_ORIGINS = True

# Modelo de usuário personalizado
AUTH_USER_MODEL = 'users.User'

# Redirecionamentos de Login
LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'core:home'
LOGOUT_REDIRECT_URL = 'users:login'

# Define o tipo padrão para chaves primárias automáticas (IDs)
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'