# Generated by Django 6.0 on 2025-12-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_denuncia_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexodenuncia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=20, null=True),
        ),
    ]
